services:
  # -------------------------
  # SERVICIO 1: BASE DE DATOS
  # -------------------------
  db:
    image: postgres:15
    container_name: bughunter-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bughunter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bughunter-net

  # -------------------------
  # SERVICIO 2: BACKEND (API)
  # -------------------------
  backend:
    # IMAGEN PARA DOCKER HUB
    image: maxcarrion31/bughunter-backend:v1.0.0
    container_name: bughunter-backend
    build:
      context: ./bughunter-api/bughunter-api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bughunter_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - bughunter-net

  # -------------------------
  # SERVICIO 3: FRONTEND (NEXTJS)
  # -------------------------
  frontend:
    # IMAGEN PARA DOCKER HUB
    image: maxcarrion31/bughunter-frontend:v1.0.0
    container_name: bughunter-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - backend # 
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - bughunter-net

volumes:
  postgres-data:

networks:
  bughunter-net: